### ISSUE TITLE
notifyURL not working

### ISSUE THREAD

**Issue by ghost** [winann/IntegratedAlipay#2]
hi, i integrated SDK to my ap success but  notifyURL not working
i want to save database buyer id, item id,  and amount  like this

notifyURL:@"http://mydomain.com/order.php?uid=2&itemid=10&amount=10"
this is my custom php file

paid success but notifyURL not work 
how can i solvce this

**Comment by winann** [comment]
You can change your URL and try it again. If it not working, neither, please contact with Alipay team.

Thank you for suport!
